# Generated by Django 4.1.1 on 2022-09-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_doner_information_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood_doner_info',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
